<?php

/**
 * Implements hook_commerce_product_info().
 */
function ee_license_role_commerce_product_type_info() {
  $product_types = array();

  $product_types['ee_license_role'] = array(
    'type' => 'ee_license_role',
    'name' => t('License Role'),
    'description' => t('A license product for selling subscriptions to access content.'),
  );

  return $product_types;
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function ee_license_role_commerce_line_item_type_info() {
  $line_item_types = array();

  $line_item_types['ee_license_role'] = array(
    'type' => 'ee_license_role',
    'name' => t('License Role'),
    'description' => t('References a product and displays it with the SKU as the label.'),
    'product' => TRUE,
    'add_form_submit_value' => t('Add License'),
    'base' => 'commerce_product_line_item',
  );

  return $line_item_types;
}
